// Copyright 2023 zzeneg (@zzeneg)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#include_next <lv_conf.h>

#undef LV_FONT_DEFAULT
#define LV_FONT_DEFAULT NULL

#undef LV_FONT_MONTSERRAT_12
#define LV_FONT_MONTSERRAT_12 0

#undef LV_FONT_MONTSERRAT_14
#define LV_FONT_MONTSERRAT_14 0

#undef LV_FONT_MONTSERRAT_16
#define LV_FONT_MONTSERRAT_16 0

#undef LV_FONT_MONTSERRAT_18
#define LV_FONT_MONTSERRAT_18 0

#undef LV_FONT_MONTSERRAT_20
#define LV_FONT_MONTSERRAT_20 0

#undef LV_FONT_MONTSERRAT_22
#define LV_FONT_MONTSERRAT_22 0

#undef LV_FONT_MONTSERRAT_24
#define LV_FONT_MONTSERRAT_24 0

#undef LV_FONT_MONTSERRAT_26
#define LV_FONT_MONTSERRAT_26 0

#undef LV_FONT_MONTSERRAT_28
#define LV_FONT_MONTSERRAT_28 0

#undef LV_FONT_MONTSERRAT_28
#define LV_FONT_MONTSERRAT_28 0

#undef LV_FONT_MONTSERRAT_30
#define LV_FONT_MONTSERRAT_30 0

#undef LV_FONT_MONTSERRAT_32
#define LV_FONT_MONTSERRAT_32 0

#undef LV_FONT_MONTSERRAT_34
#define LV_FONT_MONTSERRAT_34 0

#undef LV_FONT_MONTSERRAT_36
#define LV_FONT_MONTSERRAT_36 0

#undef LV_FONT_MONTSERRAT_38
#define LV_FONT_MONTSERRAT_38 0

#undef LV_FONT_MONTSERRAT_40
#define LV_FONT_MONTSERRAT_40 0

#undef LV_FONT_MONTSERRAT_42
#define LV_FONT_MONTSERRAT_42 0

#undef LV_FONT_MONTSERRAT_44
#define LV_FONT_MONTSERRAT_44 0

#undef LV_FONT_MONTSERRAT_46
#define LV_FONT_MONTSERRAT_46 0

#undef LV_FONT_MONTSERRAT_48
#define LV_FONT_MONTSERRAT_48 0

#undef LV_USE_GIF
#define LV_USE_GIF 1

#undef LV_TXT_ENC
#define LV_TXT_ENC LV_TXT_ENC_UTF8

#ifdef LV_USE_FONT_SUBPX
#undef LV_USE_FONT_SUBPX
#endif
#define LV_USE_FONT_SUBPX 1
#define LV_FONT_SUBPX_BGR 0

// #ifdef MIN
// #undef MIN
// #endif
// #ifdef MAX
// #undef MAX
// #endif

// #undef LV_FONT_MONTSERRAT_20
// #define LV_FONT_MONTSERRAT_20 1

// #undef LV_FONT_MONTSERRAT_36
// #define LV_FONT_MONTSERRAT_36 1
